[FIX] account: allow resetting own invoices to draft
Steps to reproduce:
- Install the `accountant` module.
- Go to Settings and make sure `Review data` is disabled.
- Open the `Mitchell Admin` user record and set the `Accounting` access
  right to `Invoicing & Banks`.
- Create and confirm a new invoice.
- Click `Reset to Draft`.

Error:
AccessError: You don't have the access rights to perform this action.

Expected Behavior:
When `Review data` is disabled, users should be able to reset their own
invoices to draft.

Root Cause:
At [1], the review state access check is always enforced when resetting an
invoice to draft, even when the Review data feature is disabled. As a result,
users cannot reset their own invoices to draft.

Fix:
This commit ensures users can reset their own invoices to draft when
Review Data is disabled.

[1]:
https://github.com/odoo/odoo/blob/0bc06aa88cbf83345ca7d266df4822430d691a5b/addons/account/models/account_move.py#L3956-L3957

opw-6409235